name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 변수출력
      env:
        ASNAME: ${{ secrets.ASNAME }}
      run: echo 내 별칭은 $ASNAME 입니다!!
