name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 변수출력
      env:
        ID: ${{ github.actor }} 
        MYASNAME:  ${{ secrets.ASNAME }} 
      run: | 
        echo "내 아이디는 $ID이고 별칭은 $MYASNAME입니다."
